name: Build

on:
  push:
    branches:
      - main

  workflow_dispatch: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      actions: write
      checks: write
      contents: write
      id-token: write
      packages: write
      statuses: write
    steps:
      - name: Cancel runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          ignore_sha: true

      - uses: actions/checkout@v2

      - name: Check cache
        id: files
        uses: actions/cache@v2
        with:
          path: app/requirements.txt
          key: app-${{ hashFiles('app/**', 'Dockerfile') }}

      - name: Python 3.8
        if: steps.files.outputs.cache-hit != 'true'
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: pip

      - name: Install
        if: steps.files.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Test
        if: steps.files.outputs.cache-hit != 'true'
        run: |
          coverage run --source=./app/ -m pytest -v
          coverage report --fail-under=60

      - name: Set up Docker Buildx
        if: steps.files.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v1

      - name: GitHub Container Registry login
        if: steps.files.outputs.cache-hit != 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Google auth
        if: steps.files.outputs.cache-hit != 'true'
        id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/644348144159/locations/global/workloadIdentityPools/eerichmond/providers/github
          service_account: ml-wildfire-service@strong-maker-345805.iam.gserviceaccount.com

      - name: Google Artifact Registry login
        if: steps.files.outputs.cache-hit != 'true'
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud auth configure-docker us-west1-docker.pkg.dev

      - name: Docker build and push
        if: steps.files.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/eerichmond/ml-wildfire-prediction:latest
            us-west1-docker.pkg.dev/strong-maker-345805/ml-wildfire/ml-wildfire:latest
          cache-from: type=registry,ref=eerichmond/ml-wildfire-prediction:latest
          cache-to: type=inline

      - name: Google Run deploy
        if: steps.files.outputs.cache-hit != 'true'
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ml-wildfire
          image: us-west1-docker.pkg.dev/strong-maker-345805/ml-wildfire/ml-wildfire:latest
          region: us-west1

      - name: URL
        if: steps.files.outputs.cache-hit != 'true'
        run: echo "${{ steps.deploy.outputs.url }}"
