name: Build

on:
  push:
    branches:
      - main

  workflow_dispatch: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      # - uses: actions/checkout@v2

      # - name: Python 3
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: 3.9
      #     cache: pip

      # - name: Install
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r app/requirements.txt

      # - name: Test
      #   run: pytest

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Docker login
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Docker build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ghcr.io/eerichmond/ml-wildfire-prediction:latest
      #     cache-from: type=registry,ref=eerichmond/ml-wildfire-prediction:latest
      #     cache-to: type=inline

      - name: Google auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/strong-maker-345805/locations/global/workloadIdentityPools/eerichmond/providers/github
          service_account: ml-wildfire-service@strong-maker-345805.iam.gserviceaccount.com

      - name: Google Run deploy
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ml-wildfire
          image: ghcr.io/eerichmond/ml-wildfire-prediction:latest

      - name: URL
        run: echo "${{ steps.deploy.outputs.url }}"
